export const FETCH_ENTITY_COUNTRY_CODES = "FETCH_ENTITY_COUNTRY_CODES";
export const FETCH_ENTITY_COUNTRY_CODES_SUCCESS = "FETCH_ENTITY_COUNTRY_CODES_SUCCESS";

export const FETCH_ENTITIES = "FETCH_ENTITIES";
export const FETCH_ENTITIES_SUCCESS = "FETCH_ENTITIES_SUCCESS";

